#┌─────────────────────────────────────────────────────┐
#│     ____  ____        __  _____  _______ __________ │
#│    / __ \/ __ \  __  /  |/  / / / / ___//  _/ ____/ │
#│   / /_/ / /_/ /_/ /_/ /|_/ / / / /\__ \ / // /      │
#│  / ____/ ____/_  __/ /  / / /_/ /___/ // // /___    │
#│ /_/   /_/     /_/ /_/  /_/\____//____/___/\____/    │
#│                                                     │
#└─────────────────────────────────────────────────────┘

[cosmology]
Omega_m            = 0.2607
Omega_L            = 0.69033
Omega_b            = 0.04897
Omvac              = -1.0
H0                 = 67.35
nspec              = 0.9649
As                 = 2.100e-9
sigma_8            = 0.8111
tau                = 0.0544
mnu                = 0.0

pkfile             = planck18_intermittent.dat

w0=                  -1.0
#wa=                 0.0
sugiyama_corr=       true
transfer=            camb_file
transfer_file=       camb.dat

[random]
seed[4]=             61316
seed[5]=             66543
seed[6]=             41387
seed[7]=             12295
seed[8]=             23456
seed[9]=             34567
seed[10]=            45678
#seed[11]=           56789
#seed[12]=           67890
seed               = 13579
chi_seed           = 90101

#┌──────────────────────────────────────────────────────┐
#│     ____             __               __       __    │
#│    / __ \___  ____ _/ /______  ____ _/ /______/ /_   │
#│   / /_/ / _ \/ __ `/ //_/ __ \/ __ `/ __/ ___/ __ \  │
#│  / ____/  __/ /_/ / ,< / /_/ / /_/ / /_/ /__/ / / /  │
#│ /_/    \___/\__,_/_/|_/ .___/\__,_/\__/\___/_/ /_/   │
#│                      /_/                             │
#└──────────────────────────────────────────────────────┘
# PeakPatch Config Begin

[boolean_switches]
hpkvd_params          = 1
compile_hpkvd         = 1
create_filterbank     = 1
merge_params          = 1
compile_merge         = 1
map_params            = 1
compile_maps          = 1
batch                 = 1
submit                = 0
 
[machine_params]
machine               = niagara
queue                 = sandyq
submit_command        = sbatch
 
[peak_patch_main]
run_name              = n288_nb32_nt2_z0
short_name            = 1100Mpc_nb27
runtype               = single
 
[box_params]
nmesh                 = 288
nbuff                 = 32
ntile                 = 2
largerun              = 0
 
[parallelization_params]
tlimit                = '1:00:00
nnodes                = 1
tpnode                = 2
ntasks                = -1
ncpus                 = 1
nompth                = 1
 
[parallelization_params_websky]
tlimit_map            = '24:00:0
nnodes_map            = 1
ppn_map               = 1
ntasks_map            = -1
np_map                = 40
nompth_map            = 1
 
[redshifts]
ievol                 = 1
num_redshifts         = 1
maximum_redshift      =   0.1100000E+04
global_redshift       =   0.0000000E+00
 
[peak_displacement]
ilpt                  = 2
ioutfield             = 1
ireadfield            = 1
iwant_field_part      = 0
fielddir              = fields/
densfilein            = -1
densfileout           = -1
 
[nongaussianities]
NonGauss              = 0
fNL                   =   0.0000000E+00
A_nG                  =   0.0000000E+00
B_nG                  =   0.0000000E+00
R_nG                  =   0.0000000E+00
m_phi                 =   0.1000000E+01
m_chi                 =   0.3565000E+02
phi_w                 =   0.1000000E+00
phi_p                 =   0.8000000E+01
vev                   =   0.1000000E+00
m_tach                =   0.4000000E+02
a_e                   =   0.1000000E-51
lcode                 =   2.6259e-52
acode_approx          =   0.3000000E+01
nk                    = 100
k0                    =  -1.0
kn                    =  -1.0
dk                    =  -1.0
kmax                  =  -1.0
H_e                   =   0.0000000E+00
 
[merging_algorithm]
iZeld                 = -1
ntilemerge            = -1
ntasksmerge           = -1
iwrap                 = 0
 
[websky_parameters]
maps                  = tsz ksz kap
nside_map             = 1024
npix_map              = 1024
fov_map               =   0.4000000E+01
zmin_map              =   0.3400000E+01
zmax_map              =   0.8100000E+01
tabfile_map           = bbps_1.tab
tabfile_sfr           = sfr_behroozi.dat
model_map             = 1
scramble_map          = 0
center_map            = 0
chihview_map          = 0
PSZcut_map            = 0
ellmax                = 512
 
 
[ellipsoidal_collapse]
ioutshear             = 0
rmax2rs               =   0.0000000E+00
wsmooth               = 1
Rsmooth_max           =  34.0
rapi                  = cip-591-ad
TabInterpFile         = HomelTab.dat
TabInterpNx           = 151
TabInterpNy           = 20
TabInterpNz           = 20
TabInterpX1           =   0.1500000E+01
TabInterpX2           =  2.148535879499316
TabInterpY1           =   0.0000000E+00
TabInterpY2           =   0.5000000E+00
TabInterpZ1           =  -0.9999000E+00
TabInterpZ2           =   0.9999000E+00
filterfile            = tables/filter.dat
iforce_strat          = 4
ivir_strat            = 2
dcrit                 =   0.2000000E+03
fcoll_1               =   0.1000000E-01
fcoll_2               =   0.1710000E+00
fcoll_3               =   0.1710000E+00
 
[lattice_parameters_hpkvd]
nsub                  = -1
next                  = -1
dcore_box             =  -0.1000000E+01
cellsize              =  -0.1000000E+01
buffersize            =  -0.1000000E+01
dL_box                =  -0.1000000E+01
mlatt                 =  -0.1000000E+01
cenx                  =   0.0000000E+00
ceny                  =   0.0000000E+00
cenz                  =  0.0
nlx                   = -1
nly                   = -1
nlz                   = -1
n1                    = 320
n2                    = 320
n3                    = 320
 
[advanced_merge_parameters]
iLexc                 = 3
iLmrg                 = 0
iFexc                 = 0
iFmrg                 = 0

#┌───────────────────────────────────┐
#│     __  _____  _______ __________ │
#│    /  |/  / / / / ___//  _/ ____/ │
#│   / /|_/ / / / /\__ \ / // /      │
#│  / /  / / /_/ /___/ // // /___    │
#│ /_/  /_/\____//____/___/\____/    │
#│                                   │
#└───────────────────────────────────┘
# MUSIC Config Begin

[setup]
boxlength             = 1248
zstart=                 0
region=                 box
levelmin=               9
#levelmin_TF=           8
levelmax=               9
#padding=               4
#overlap=               2
#ref_center=            0.485,  0.43, 0.173
#ref_extent=            0.1, 0.1, 0.1
align_top=              no
baryons=                no
use_2LPT=               yes
use_LLA=                yes
periodic_TF=            yes
calculate_potential= 	no
calculate_displacements=no
calculate_velocities= 	no


[output]
##Gadget-2 (type=1: high-res particles, type=5: rest)
format=                 peakpatch
gadget_usekpc=          yes
gadget_coarsetype=      2
filename=               ../IC_dmonly.dat

[poisson]
fft_fine=               no
accuracy=               1e-5
pre_smooth=             3
post_smooth=            3
smoother=               gs
laplace_order=          6
grad_order=             6
